### ISSUE TITLE
Too opinionated

### ISSUE THREAD

**Issue by darrenscerri** [croudcare/relpers#2]
I really like the idea of a repository dedicated to React helpers and would be really interested to contribute to it but I would think that each helper needs to be very unopinionated and generic. For example, the `injectProps` helper fits perfectly in this repo but components like Input and Form are not. There are a lot of assumptions taken as to how these components should behave and they don't really fit in the idea of a helper.

For example instead of an Input and Form component we can implement a FormElement helper which can decorate a React Component as a form element, with whatever that can be concluded to mean (has an onChange, onValid, onInvalid, internal state, etc.).

I really believe in this repo but I think its contents have to change to make it more fitting and useful in generic cases.

**Comment by goncalvesjoao** [comment]
I concur 100%.
Will make a v1.1 shortly.

**Comment by goncalvesjoao** [comment]
#4 adds a clean slate to master and from now on, new additions will be decided by the general public aka developers that use the package.

**Comment by darrenscerri** [comment]
Great!
